# Generated by Django 2.2.6 on 2019-10-26 19:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('rid', models.IntegerField(primary_key=True, serialize=False)),
                ('mobile_no', models.CharField(max_length=10, unique=True)),
                ('email_id', models.EmailField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NGO',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('nid', models.IntegerField(primary_key=True, serialize=False)),
                ('mobile_no', models.CharField(max_length=10, unique=True)),
                ('email_id', models.EmailField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
