# Generated by Django 2.2.6 on 2019-10-28 18:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KhaanDaanUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('mobile_no', models.CharField(max_length=10, unique=True)),
                ('email_id', models.EmailField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('user_type', models.CharField(choices=[('R', 'Restaurant'), ('N', 'NGO')], max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
