# Generated by Django 2.0.1 on 2019-10-27 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ngo',
            name='user_type',
            field=models.CharField(choices=[('R', 'Restaurant'), ('N', 'NGO')], default='N', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='user_type',
            field=models.CharField(choices=[('R', 'Restaurant'), ('N', 'NGO')], default='R', max_length=20),
            preserve_default=False,
        ),
    ]
