# Generated by Django 2.0.1 on 2019-10-26 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20191026_1426'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NGO',
        ),
        migrations.DeleteModel(
            name='Restaurant',
        ),
    ]
