# Generated by Django 2.0.1 on 2019-09-01 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NGO',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('nid', models.IntegerField(primary_key=True, serialize=False)),
                ('mobile_no', models.CharField(max_length=10, unique=True)),
                ('email_id', models.EmailField(max_length=100)),
                ('address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('rid', models.IntegerField(primary_key=True, serialize=False)),
                ('mobile_no', models.CharField(max_length=10, unique=True)),
                ('email_id', models.EmailField(max_length=100)),
                ('address', models.CharField(max_length=200)),
            ],
        ),
    ]
