# Generated by Django 2.0.1 on 2019-10-29 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_food_served_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='served_to',
        ),
    ]
