# Generated by Django 2.0.1 on 2019-10-29 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_remove_food_served_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='served_to',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
