# Generated by Django 2.0.1 on 2019-10-30 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_food_served_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='food_type',
            field=models.CharField(choices=[('N', 'Non-veg'), ('V', 'Veg')], max_length=50),
        ),
    ]
